---
output: 
  html_document:
    toc: true
    toc_float: true
---

# Resume

The pdf attachment of my resume is also available [here](Resume_10_10_19.pdf).

## Experience

* **University of California San Francisco (UCSF), San Francisco, CA — Biostatistics Intern**

  JUNE 2018 - AUGUST 2018 & JUNE 2019 - AUGUST 2019
  
  - Used statistical matching to analyze postoperative effects between awake and asleep glioblastoma patients 
  
  - Performed survival analysis and visualized low grade glioblastoma clinical neurosurgery data on patient survival status using R and JMP 
  
  - Cleaned and manipulated clinical data ranging from 200 to 800 patients
  
  - Facilitated literature review research for meta-analysis paper on association of glioblastoma survival status and extent of resection

* **Beijing United Family Hospital (北京和睦家医院), Beijing, China — Marketing Intern**

  JANUARY 2018 - MAY 2018
  
  - Performed Chinese to English medical translations for marketing Powerpoints and informational pamphlets 
  
  - Analyzed 400 rows of recruitment hospital data with SAS looking at client influx from 6 relocation agencies to allocate  marketing resources 

* **Elite Educational Institution, San Francisco, CA — Office Student Assistant** 

  SUMMER 2015 - SUMMER 2019
  
  - Organized and distributed 8 weeks of SAT math, reading, and writing quiz curriculum for 13 different SAT class sections
  
  - Scheduled tutoring appointments and processed cash, cheque, and card payments in both English & Mandarin
  
## Skills 

* **Data Analytics & Visualization** 
  - R 
  - SAS
  - Tableau
  - SQL (Oracle, Teradata)
  - JMP
* **Final Cut Pro X Proficiency**

* **Microsoft Word Business Proficiency**
  - Word (Mail Merge)
  - Excel (Pivot Tables, Scenario Manager, Goal Seek, Solver)
  - Access (Queries, Forms, Reports, Macros)  
  
* **Database Modeling**
  - Entity-relationship modeling
  - Relational modeling

## Education

* **Columbia University Mailman School of Public Health, New York, NY — Master of Science**

  AUGUST 2019 - MAY 2021 (Expected)
  
  - M.S. in Biostatistics

* **Loyola University Chicago, Chicago, IL — Bachelor of Science**

  AUGUST 2015 - MAY 2019 
  
  - B.S. with Honors in Statistics, minor in Information Systems
  
* **The Beijing Center, Beijing, China — Affiliated with University of International Business and Economics（对外经济贸易大学）**

  JANUARY 2018 - MAY 2018
  
  - Immersive study abroad program dedicated to promoting U.S. and China academic and student relations
  
## Languages

* **English**
  - Native Speaker

* **Chinese (Mandarin)**
  - Intermediate working proficiency - Fluent: Speaking
  - Intermediate: Reading, Writing

## Awards

* **College of Arts and Science Dean’s List Recipient**
  - Recognition of full time students who earn at least a 3.5 GPA

* **Loyola University Chicago Honors Program**
  - Merit-based writing intensive program comprised of 10% of students in the Class of 2019
  
* **The Beijing Center Merit-Based Study Abroad Scholarship**

* **Loyola University Chicago Damen Academic Merit Scholarship**

* **The Band of Wolves Pep Band Scholarship**
  - Requires members to attend at least 85% of rehearsals and games

## Activities 

* **American Statistical Association Datafest, Chicago, IL**

  MARCH 2017
  - Utilized SAS and Tableau to analyze travel agency data to find correlations between location and number of bookings for potential marketing purposes
  



